# Generated by Django 5.1.4 on 2024-12-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmst',
            old_name='product_name',
            new_name='pname',
        ),
    ]
